services:
  - type: web
    name: freescout
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: FILESYSTEM_DRIVER
        value: public
      - key: APP_KEY
        value: ""
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ""
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: ""
      - key: DB_USERNAME
        value: ""
      - key: DB_PASSWORD
        value: ""
